services:
  app:
    container_name: lesson_fe
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "12000:3000"
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"
volumes:
  node_modules:
